service: royalswing-telegram-bot

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-3
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}

functions:
  webhook:
    handler: handler.webhook
    events:
      - http: POST /

  set_webhook:
    handler: handler.set_webhook
    events:
      - http: POST /set_webhook

plugins:
  - serverless-python-requirements